# Copyright (c) 2026, ErpGenEx
# Auto-generated by Global Excellence safe_gap_fixes

import frappe
from frappe import _


def execute(filters=None):
	filters = frappe._dict(filters or {})
	conditions = ["1=1"]
	pass
	where_clause = " AND ".join(conditions)
	data = frappe.db.sql(
		f"""
		SELECT `name`, `tenant_name`, `status`, `site_url`
		FROM `tabSaaS Tenant`
		WHERE {where_clause}
		ORDER BY modified DESC
		LIMIT 500
		""",
		filters,
		as_dict=True,
	)
	columns = [
		{"label": _("Name"), "fieldname": "name", "fieldtype": "Link", "width": 140},
		{"label": _("Tenant Name"), "fieldname": "tenant_name", "fieldtype": "Data", "width": 180},
		{"label": _("Status"), "fieldname": "status", "fieldtype": "Data", "width": 100},
		{"label": _("Site URL"), "fieldname": "site_url", "fieldtype": "Data", "width": 200}
	]
	return columns, data
