# Copyright (c) 2026, ErpGenEx
# Auto-generated by Global Excellence safe_gap_fixes

import frappe
from frappe import _


def execute(filters=None):
	filters = frappe._dict(filters or {})
	conditions = ["1=1"]
	pass
	where_clause = " AND ".join(conditions)
	data = frappe.db.sql(
		f"""
		SELECT `name`, `application_name`, `is_active`
		FROM `tabSaaS Application`
		WHERE {where_clause}
		ORDER BY modified DESC
		LIMIT 500
		""",
		filters,
		as_dict=True,
	)
	columns = [
		{"label": _("Name"), "fieldname": "name", "fieldtype": "Link", "width": 140},
		{"label": _("Application Name"), "fieldname": "application_name", "fieldtype": "Data", "width": 180},
		{"label": _("Is Active"), "fieldname": "is_active", "fieldtype": "Check", "width": 80}
	]
	return columns, data
